version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: distributo-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-distributo}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-distributo_dev}
      POSTGRES_DB: ${POSTGRES_DB:-distributo}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-distributo}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: distributo-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data: 